### ISSUE TITLE
timing: students barely started the exercise

### ISSUE THREAD

**Issue by jsms90** [foundersandcoders/error-handling-workshop#17]
The content of this workshop is absolutely brilliant!! But most of FAC11 barely got to the actual [exercise](https://github.com/foundersandcoders/error-handling-workshop#exercise-error-handling--server-side-validation). They had just written / were about to write their first test at the end of the 2 hours.

+ [x] Large amount of conceptual information to read through before getting to the exercise. Might be helpful to have the exercise earlier, since it provides some context. #23 

+ [x] Unfamiliar file structure - just took time for them to explore and figure out without an explanation #19 

+ [x] Clarity of instructions
  + [x] Context: Spec is largely unconnected to the context provided in the "Problem" section i.e. kittehs in space
  + [x] Describe the files that already exist & how they connect #20 
  + [x] Each step is really large, so it's difficult for students to say "I've finished step x, now I'm on step x+1" #21 
  + [x] Not completely obvious _what_ students are supposed to write i.e. to go step by step through the requirements
  + [x] Jump between step 2 and 3 - students shouldn't put all validation in `validateFilename.js` but create `validateContent.js`, etc.

+ [x] Provided solution doesn't match instructions - it's all in one file #22 
  + [x] Missing tests from solution e.g. testing validate functions - @majakudlicka providing simple example of first step using TDD #16

**Comment by eliascodes** [comment]
@jsms90 if it's OK with you, I'm going to break this up into smaller issues (a bit like you did with #16) to help make the PRs smaller.

**Comment by jsms90** [comment]
@eliascodes 100%. I've made this as a kind of "epic" but I didn't want to overload you with issues until you'd had a chance to look at it. We're also going through this with FAC11 now, so I'll edit it with anything else that we find about what confused people

**Comment by jsms90** [comment]
Most of the cohort spent the whole time trying to get their hand around the readme. Since they didn't reach the exercise, they didn't have a chance to go through the steps themselves.

So it seems like @majakudlicka's walkthrough yesterday afternoon was illuminating for anyone who grasped the concepts in the readme, but just didn't have a chance to put it into practice themselves. Whereas, for those who felt like the content of the readme went over their heads, the walkthrough was completely overwhelming.

I offered an extra session after 6pm yesterday / before 10am today. 6 students attended.

The main confusion points were:
+ how error handling relates to a real world application e.g. projects they've done before
  + **more context would help** e.g. relate the spec to the kittens who are going to space and/or create a frontend where an actual form is submitted
  + explain what "handling" an error actually means
  + contextual example of when to use each of the approaches to error handling
+ understanding that the entire exercise was about writing one handler (the handler for one route) and therefore having all these different files are just because we're trying to write our code in a modular way
+ what shot is for and when to use it - don't need it in `validateFilename.test.js`
+ understanding that the "Steps" of the exercise are derived from the specification
  + they created `validateFilename.js` because they were explicitly told to, rather than understanding that this is directly related to the first line in the requirements
  + jump between step 2 & 3 - didn't understand that they would also need to create `validateContent.js` and `validate.js`
  + problems understanding how `validateFilename.js` relates to the handler
+ understanding what `createRecord` is doing
+ solution folder contains only one file & the code for step 2 is in the middle of the file

**Comment by eliascodes** [comment]
On shot:
> what shot is for and when to use it - don't need it in validateFilename.test.js

They've just had the shot/TDD workshop, they should know what it is?

**Comment by eliascodes** [comment]
The final exercise is now not formally a part of the workshops, so closing this as no longer relevant.
